channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  - pip >=22.2.2
  - gdal >=3.4.3
  - affine >=2.3.1
  - Fiona >=1.8.21
  - pyproj >=3.4.0
  - pandas >=1.4.4
  - geopandas >=0.11.1
  - Rtree >=1.0.0
  - matplotlib >=3.5.3
  - Shapely >=1.8.4,<2
  - rasterio >=1.2.10
  - netCDF4 >=1.6.1
  - geopy >=2.2.0
  - pip:
      - loguru >=0.6.0
      - pytest >=7.1.3
      - pytest-cov >=3.0.0
