site_name: pyramids
site_description: The documentation of Hapi Hydrological Model
site_author: Mostafa Farrag

repo_url: https://github.com/MAfarrag/pyramids
edit_url: ""

theme:
    name: readthedocs

nav:
    - Home: index.md
    - GIS: GIS.md
    - License: license.md
