channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - pip >=22.3.1
  - pandas
  - numpy==1.20.*
  - numpydoc==1.1.0
  - typing-extensions==3.10.*
  - pip:
    - pydata-sphinx-theme
    - nbsphinx